version: '3.7'

volumes:
  dependency-track:
  dependency-frontend:


services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:${VERSION}
    env_file:
      - ./.env.example
    ports:
      - '8081:8080'
    volumes:
      - 'dependency-track:/data'
      - "./${PATH_TO_CACERTS}:/opt/java/openjdk/lib/security/cacerts:ro"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:${VERSION}
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=${API_BASE_URL}
    volumes:
      - 'dependency-frontend:/data' # Read-only volume for frontend data
      - './${_data/reverse.conf}:/etc/nginx/conf.d/reverse.conf' # Read-only volume for Nginx configuration
      - './${PATH_TO_PEM}:/etc/nginx/certs/${PEM_FILE}'
      - './${PATH_TO_KEY}:/etc/ssl/private/${KEY_FILE}'
      - "./${PATH_TO_CACERTS:/opt/java/openjdk/lib/security/cacerts:ro"
    ports:
      - '443:443' # Expose HTTPS on port 443 (map to internal container port 443)
    restart: unless-stopped